### ISSUE TITLE
请怎样把混音保存到文件里面呢?

### ISSUE THREAD

**Issue by ChendayUP** [JustinYangJing/VoiceMixer#1]
请怎样把混音保存到文件里面呢?

**Comment by JustinYangJing** [comment]
点击底部的混音记录，可以记录混音，运行时，打打印写入手机的音频文件名，如果是真机运行，在Xcode选择"Device and Simulators" 选中手机里面的VoiceMixer app , 点击窗口下方的 ”⚙“图标， 选中"Download Container", 录音文件在  AppData/Documents文件夹下
