### ISSUE TITLE
录音和背景音乐并没有混进去

### ISSUE THREAD

**Issue by sunchengxiu** [JustinYangJing/VoiceMixer#2]
录音和背景音乐并没有混进去，而且audioSession 改成这样，  [sessionInstance setCategory:AVAudioSessionCategoryPlayAndRecord  withOptions:AVAudioSessionCategoryOptionDefaultToSpeaker  error:&error];

会有惊天地的效果，您看能解决吗

**Comment by JustinYangJing** [comment]
我这边模拟器和真机都测了一遍， 背景音和录音混合，点击录入，从沙盒里面取到的录音文件里面有背景音和录音。 withOptions:AVAudioSessionCategoryOptionDefaultToSpeaker设置为这个以后， 测试即使带了蓝牙耳塞也是通过Speaker播放
